### ISSUE TITLE
Overwrite hardcoded parser

### ISSUE THREAD

**Issue by MrMoronIV** [Genert/bbcode#12]
Inside `Parser/BBCodeParser.php` there is:
```
    protected $parsers = [
        'h1' => [
            'pattern' => '/\[h1\](.*?)\[\/h1\]/s',
            'replace' => '<h1>$1</h1>',
            'content' => '$1'
        ],
```
However, when I add my own parser for h1 using `$bbCode->addParser` it doesn't replace the hardcoded one, is there a way to get rid of it without changing the source code?

**Comment by Genert** [comment]
Fixed this with in the following commit - https://github.com/Genert/bbcode/commit/226a25bcfa37a7d81d2f400cd7f736ff31cf9a08

Please update your composer to include the newest version of this library.
