### ISSUE TITLE
Question: How do I add this without using composer?

### ISSUE THREAD

**Issue by Maveee** [Genert/bbcode#3]
Your code is exactly what I need as I read data from a forum and use them somewhere else using php.
My current problem is that stuff is displayed like this:

[img width=999]https://i.imgur.com/9TJYi69.png[/img]
[list]
[li]+3 for every hour online[/li]
[li]+3 for every challenge won[/li]
[li]+5 for every hard challenge won[/li]
[li]+3 for every race won[/li]
[li]+1 for every reaction test won[/li]
[li]+1 for every maths test won[/li]
[li]+2 for every kill in a deathmatch[/li]
[/list]

inside html. So using your code would be perfect. However I do not use Composer. 
Could you please add installation instructions for adding this manually? Thank you!

**Comment by chrisx84** [comment]
well you should getcomposer.org but its kinda easy without it, just download from this repo and just require or include to src/BBCode.php

**Comment by zwantE** [comment]
dont work "Fatal error: Uncaught Error: Class 'Genert\BBCode\Parser\HTMLParser' not found in ***"
path is correct :/

**Comment by Genert** [comment]
You need to change namespaces.

The Composer uses "Genert\BBCode\" as "src" folder path.

You need to strip part from the namespace.

Otherwise, I suggest to use Composer. It really is handy in PHP world.
