### ISSUE TITLE
How do I process this BBCode?

### ISSUE THREAD

**Issue by TheBigK** [Genert/bbcode#4]
I can't thank you enough for this life-saver! You've just saved me at least 100 hours. I would be thankful to you if you could help me process the following type of BBCode -

`[QUOTE="John Doe, post: 361365, member: 1003"]Some Random Quote[/QUOTE]`

I need to extract the user name, post Id, member id and also the quote and parse it into HTML. But for the life of me, I can't figure out how to write the correct pattern for this. 

Would really appreciate your help. Thank you once again!

**Comment by Genert** [comment]
This feature will be investigated and developed. See #10
